version: '3'
services:
    promgateway:
        image: prom/pushgateway:latest
        restart: always
        ports:
            - 9091:9091
    prom:
        image: prom/prometheus:latest
        restart: always
        ports:
            - 9090:9090
        depends_on:
            - promgateway
        volumes:
            - .\prometheus:/etc/prometheus/
            - .\prometheus\data:/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/usr/share/prometheus/console_libraries'
            - '--web.console.templates=/usr/share/prometheus/consoles'
    grafana:
        image: grafana/grafana
        depends_on:
            - prom
        ports:
            - 3000:3000
            
