// <auto-generated />
using BeatPulse.UI.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace BeatPulse.UI.Core.Data.Migrations
{
    [DbContext(typeof(LivenessDb))]
    [Migration("20180430155057_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("BeatPulse.UI.Core.Data.LivenessConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("LivenessName")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("LivenessUri")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.ToTable("LivenessConfigurations");
                });

            modelBuilder.Entity("BeatPulse.UI.Core.Data.LivenessExecution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsHealthy");

                    b.Property<DateTime>("LastExecuted");

                    b.Property<string>("LivenessName")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("LivenessResult")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<string>("LivenessUri")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<DateTime>("OnStateFrom");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("LivenessExecutions");
                });

            modelBuilder.Entity("BeatPulse.UI.Core.Data.LivenessExecutionHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("LivenessExecutionId");

                    b.Property<DateTime>("On");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("LivenessExecutionId");

                    b.ToTable("LivenessExecutionHistory");
                });

            modelBuilder.Entity("BeatPulse.UI.Core.Data.LivenessFailureNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("LastNotified");

                    b.Property<string>("LivenessName")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.ToTable("LivenessFailuresNotifications");
                });

            modelBuilder.Entity("BeatPulse.UI.Core.Data.LivenessExecutionHistory", b =>
                {
                    b.HasOne("BeatPulse.UI.Core.Data.LivenessExecution")
                        .WithMany("History")
                        .HasForeignKey("LivenessExecutionId");
                });
#pragma warning restore 612, 618
        }
    }
}
