// <auto-generated />
using BeatPulse.UI.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace BeatPulse.UI.Core.Data.Migrations
{
    [DbContext(typeof(LivenessContext))]
    [Migration("20180401094010_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("BeatPulse.UI.Core.Data.LivenessConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("LivenessName")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("LivenessUri")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.ToTable("LivenessConfiguration");
                });

            modelBuilder.Entity("BeatPulse.UI.Core.Data.LivenessExecutionHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ExecutedOn");

                    b.Property<bool>("IsHealthy");

                    b.Property<string>("LivenessName")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("LivenessUri")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.HasKey("Id");

                    b.ToTable("LivenessExecutionHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
